class ClassSalonJoinUser {
  String id,
      username,
      namasalon,
      alamat,
      kota,
      telp,
      longitude,
      latitude,
      keterangan,
      status,
      foto,
      pembayaran,
      jambuka,
      jamtutup,
      hari,
      kategori;

  ClassSalonJoinUser(
      this.id,
      this.username,
      this.namasalon,
      this.alamat,
      this.kota,
      this.telp,
      this.longitude,
      this.latitude,
      this.keterangan,
      this.status,
      this.foto,
      this.pembayaran,
      this.jambuka,
      this.jamtutup,
      this.hari,
      this.kategori);
}
