class ClassLayanansalon {
  String id,
      idsalon,
      username,
      namalayanan,
      jumlah_kursi,
      peruntukan,
      jenjangusia,
      idkategori,
      hargapriadewasa,
      harganwanitadewasa,
      hargawanitaanak,
      hargapriaanak,
      durasi,
      deskripsi,
      status,
      keterlambatan_waktu,
      foto;

  ClassLayanansalon(
      this.id,
      this.idsalon,
      this.username,
      this.namalayanan,
      this.peruntukan,
      this.idkategori,
      this.jenjangusia,
      this.durasi,
      this.deskripsi,
      this.status,
      this.hargapriadewasa,
      this.harganwanitadewasa,
      this.hargapriaanak,
      this.hargawanitaanak,
      this.jumlah_kursi,
      this.keterlambatan_waktu,
      this.foto);
}
