class ClassUserJoinSalonJoinJadwalsalon {
  String email,
      username,
      password,
      nama,
      alamat,
      kota,
      telp,
      foto,
      saldo,
      tgllahir,
      jeniskelamin,
      role,
      status,
      idsalon,
      hari,
      jambuka,
      jamtutup;

  ClassUserJoinSalonJoinJadwalsalon(
      this.email,
      this.username,
      this.password,
      this.nama,
      this.alamat,
      this.kota,
      this.telp,
      this.foto,
      this.saldo,
      this.tgllahir,
      this.jeniskelamin,
      this.role,
      this.status,
      this.idsalon,
      this.hari,
      this.jambuka,
      this.jamtutup);
}
